#!/usr/bin/env python

import time, os

def makehead(reportfile, name):
	reportfile.write("<html>\n")
	reportfile.write("<head>\n")
	reportfile.write("<style type='text/css'>\n")
	reportfile.write("   html, body {height: 100%; margin: 0}\n")
	reportfile.write("	#content {width: 100%; height: 100%}\n")
	reportfile.write("	#left {width: 150px; height: 100%; float: left;}\n")
	reportfile.write("	#right {margin-left: 170px; height: 100%;}\n")
	reportfile.write("</style>\n")
	reportfile.write("<link rel=\"stylesheet\" href=\"report.css\" type=\"text/css\"/>\n")
	reportfile.write("<h1><div align=center> AFFT reportfile - " + name + " </div></h1>\n")
	reportfiledate = time.strftime("%d/%m/%Y")
	reportfiletime = time.strftime("%H:%M:%S")
	reportfile.write("   <p>Report compiled on " + reportfiledate + " at " + reportfiletime + " </p>\n")
	reportfile.write("   <p>Generated by Android Free Forensic Toolkit. &copy; Conor Rynne</p>\n")
	reportfile.write("</head>\n")
	reportfile.write("<body>\n")
	reportfile.write("<div id='content'>\n")
	reportfile.write("<br /><br />")
	reportfile.write("  <div id='left' class=\"SideBar\">\n")
	reportfile.write("	  <table>\n")
	reportfile.write("<TR><TD>reports</TD></TR>")

def importnavbar(reportfile, case):
	navbarlocation = os.path.join(case, "reports", "navlist")
	navbar = open(navbarlocation, 'r')
	reportfile.write(navbar.read())

def makemid(reportfile):
	reportfile.write("   </table>\n")
	reportfile.write("   </div>\n")
	reportfile.write("   <div id='right'>\n")
